import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tip Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>  
    <div className='flex justify-center items-center mt-16'>
        <Image className='' src='/static/images/logo.svg' alt='Tip Calculator' width={80} height={80} ></Image>
    </div>
    <div className=' bg-white p-4 m-2 rounded-md md:mx-32 lg:mx-40 xl:mx-96'>
      <div className='w-full '>
        <form>
          <span className='text-xs '>Bill</span>
          <input type='text' className='mt-1 w-full p-2 outline-teal-500 bg-cyan-100 rounded-md mb-6' placeholder='$'></input>
          <span className='text-xs mb-4'>Select Tip %</span>
          <div className='grid grid-cols-2 gap-2 md:grid-cols-3 mt-2'>
            <button className='p-2 bg-teal-700 rounded-md text-white px-4 py-2 font-mono hover:bg-teal-500' type='button'>5 %</button>
            <button className='p-2 bg-teal-700 rounded-md text-white px-4 py-2 font-mono hover:bg-teal-500' type='button'>10 %</button>
            <button className='p-2 bg-teal-700 rounded-md text-white px-4 py-2 font-mono hover:bg-teal-500' type='button'>15 %</button>
            <button className='p-2 bg-teal-700 rounded-md text-white px-4 py-2 font-mono hover:bg-teal-500' type='button'>25 %</button>
            <button className='p-2 bg-teal-700 rounded-md text-white px-4 py-2 font-mono hover:bg-teal-500' type='button'>50 %</button>
            <input type='text' className='outline-teal-500 bg-cyan-100 p-1 w-full h-10 rounded-md placeholder:text-xs placeholder:text-center' placeholder='Custom'></input>
          </div>
        </form>
      </div>
      <div>

      </div>
    </div>
    </div>
  )
}
